services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ../backend:/var/www/html
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - frontend_data:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: feel-green
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - frontend_data:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - app_network

volumes:
  db_data:
  frontend_data:

networks:
  app_network:
