services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: a_backend
    volumes:
      - ../backend:/var/www/html
    networks:
      - app_network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: a_frontend
    volumes:
      - frontend_data:/usr/share/nginx/html
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: a_nginx
    ports:
      - "8001:80"  # http://localhost:8001/admin
      - "88:80"  # http://localhost:88/
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
      - frontend_data:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: a_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: feel-green
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - app_network

volumes:
  db_data:
  frontend_data:

networks:
  app_network:
